version: '2'
services:
    ratpack-echo:
        build: .
        image: ratpack-echo:compose
        container_name: "ratpach-echo"
        network_mode: "bridge"
        restart: always
        ports:
        - "5050:5050"
        - "2020:2020"
        environment:
            JVM_HEAP_MIN: "128m"
            JVM_HEAP_MAX: "768m"
            JVM_JMX_PORT: "2020"
            JVM_JMX_RMI_PORT: "2020"
            JVM_JMX_HOST: "10.0.2.15"
